apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "digital-account-opening-api.fullname" . }}
  labels:
    {{- include "digital-account-opening-api.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.env.PORT | quote }}
